import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "@/components/custom/Footer/Footer";
import Header from "@/components/custom/Header/Header";
import { Toaster } from "@/components/ui/toaster";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/seo/favicon.ico" sizes="any" />
        <link
          rel="apple-touch-icon"
          href="/assets/seo/apple-touch-icon.png"
        />
      </head>
      <body className="font-roboto max-w-7xl mx-auto">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="px-2 pt-2.5" >
            <Header />
          </header>
          <main className="">
            {children}
          </main>
          <Toaster/>
          <footer>
            <Footer />
              
          </footer>
      
        </ThemeProvider>
      </body>
    </html>
  );
}

