import Cta from '@/components/custom/cta/Cta'
import Faq from '@/components/custom/Faq/FAQ'
import Insights from '@/components/custom/Insights/Insights'
import TabSwitch from '@/components/custom/TabSwitch/TabSwitch'
import myFaqs from '@/public/assets/data/Insights/faq.json'
import updates from '@/public/assets/data/Insights/Insights.json'
import projects from '@/public/assets/data/works/projects.json'
import Primary from '@/components/custom/Insights/Primary'
import type { Metadata } from 'next'


export const metadata: Metadata  = {
  title: "Insights",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div>
      <TabSwitch
        index={4}
        primaryTab={{
          title: "Insights",
          count: '4',
          description: "I am a IT student and developer who is passionate about entrepreneurship. and I loves to explore new technologies. I am currently developing cool projects."
        }}

        primaryChildren={
          <Primary />
        }
      />
      <section >
        <Insights
          posts={updates.posts}
          projects={projects}
          events={updates.events}
          others={updates.others}
        />
      </section>
      <Faq title='Questions About My Work' description=' I’m a software engineer building tools like Rize and contributing to open-source at Hytek Org.' faqs={myFaqs} />
      <Cta badgeText="Let&apos;s Build Together"
        title="Want to collaborate on something amazing?"
        description="I&apos;m always open to working on innovative projects in machine learning, AI, and software development. Whether it&apos;s a startup idea, a research project, or a side hustle, let&apos;s build something great together."

        contactLink="/contact"
      />
    </div>
  )
}
